#This workflow is created to auto tag all workflow or changes made to main branch

name: auto_tag

on:
  push:
    branches:
      - main
jobs:
 tag_repo:
   name: Get Runner ID and Tag the current code snapshot
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: Tag and push current repo code
       run: |
         git tag ${{github.run_id}}
         git push origin ${{github.run_id}}
         echo "::set-output name=date::$(date +'%Y-%m-%d')"
