# This is a basic workflow to help you get started with Actions

name: Test PowerShell on Ubuntu

# Controls when the workflow will run (when pipeline will get trigger)
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab (created a button similar to build now in Jenkins)
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  powershell-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: check out repository code
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it (github actions need workflow to read)
        uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Perform a test from command line
        #shell Configures the job to use PowerShell when running the run commands.
        shell: pwsh   
        run: Get-Service | Where-Object {$_.Status -eq 'Running'}             
      - name: Run a multi-line script
        shell: pwsh
        run: Write-Host "appname" (git config --get remote.origin.url) -replace '.*/' -replace '.git'
      - name: print end results
        run: echo "pipe ends"
